- name: Install software

  hosts: all

  become: true

  tasks:
    - name: Install acl
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx
        - acl
