- name: Setup website

  hosts: all

  vars:
    username: ansible-worker
    index_local_path: "../files/index.html"
    config_local_path: "../files/ansible.iphilka.ru.conf"
    website_dir: "/home/{{ username }}/www/stud-template"
    repository_url: "git@github.com:iphilka/stud-template.git"

  tasks:
    - name: Create website directory
      ansible.builtin.file:
        path: "{{ website_dir }}"
        state: directory
        mode: u=+rwx,g=rwx,o=rx
      become: true
      become_user: "{{ username }}"

    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ repository_url }}"
        dest: "{{ website_dir }}"
        force: true
      become: true
      become_user: "{{ username }}"
      notify: Restart Nginx

    - name: Copy index page to user
      ansible.builtin.copy:
        src: "{{ index_local_path }}"
        dest: "{{ website_dir }}"
        mode: "0644"
      become: true
      become_user: "{{ username }}"
      notify: Restart Nginx

    - name: Copy nginx config
      ansible.builtin.copy:
        src: "{{ config_local_path }}"
        dest: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        mode: "0644"
      notify: Restart Nginx
      become: true

    - name: Enable iphilka site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-enabled/ansible.iphilka.ru.conf
        state: link
      notify: Restart Nginx
      become: true

    - name: Disable default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx
      become: true

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
