- name: Homework 1

  hosts: all

  vars:
    username: ansible-worker
    site_local_path: "../files/index.html"
    config_local_path: "../files/ansible.iphilka.ru.conf"
    site_dir: "/home/{{ username }}/www/"

  tasks:

    - name: Copy nginx config
      ansible.builtin.copy:
        src: "{{ config_local_path }}"
        dest: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        mode: "0644"
      notify: Restart Nginx
      become: true

    - name: Enable iphilka site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-enabled/ansible.iphilka.ru.conf
        state: link
      notify: Restart Nginx
      become: true
    
    - name: Disable default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx
      become: true

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
