- name: Homework 1

  hosts: all

  vars:
    username: ansible-worker
    site_local_path: "../www/index.html"
    site_dir: "/home/{{ username }}/www/"

  tasks:
    - name: Create www directory
      ansible.builtin.file:
        path: "{{ site_dir }}"
        state: directory
        mode: "0744"
      become: true
      become_user: "{{ username }}"

    - name: Clone repository
      ansible.builtin.git:
        repo: git@github.com:iphilka/stud-template.git
        dest: "{{ site_dir }}"
        force: true
      become: true
      become_user: "{{ username }}"

    - name: Copy index page to user
      ansible.builtin.copy:
        src: "{{ site_local_path }}"
        dest: "{{ site_dir }}"
        mode: "0644"
      become: true
      become_user: "{{ username }}"

